### ISSUE TITLE
[FEATURE] Books tracking

### ISSUE THREAD

**Issue by shazxrin** [very-indecisive-studios/tracktgt-server#17]
### **Feature description**

This feature allows frontend to track books for users. Books to be tracked will have the following tracked information:

- Chapters Read
- Format Owned (i.e Digital, Physical)
- Status (i.e Completed, Reading, Paused, Planning)
- Game Ownership (i.e Owned, Loaned, Wishlist)

A book can only be tracked once unlike games.

### **Describe the feature deliverables**

***Core logic***
- [x] Book tracking
  - [x] Add book to be tracked by its unique id with tracked information
  - [x] Delete book tracking
  - [x] Modify book tracking's information
  - [x] View all book trackings by user
    - [x] Paging support
    - [x] Filters and sorting support
  - [x] View book trackings made for a book by a user

***Tests***
- [x] Book tracking
  - [x] Add book to be tracked by its unique id with tracked information
  - [x] Delete book tracking
  - [x] Modify book tracking's information
  - [x] View all book trackings by user
  - [x] View book trackings made for a book by a user
