### ISSUE TITLE
[FEATURE] Shows tracking

### ISSUE THREAD

**Issue by Mehvin** [very-indecisive-studios/tracktgt-server#20]
### **Feature description**

This feature allows frontend to track shows for users. Shows to be tracked will have the following tracked information:

- Episodes Watched (For movies, 1 - watched & 0 - not watched)
- Status (i.e Completed, Watching, Paused, Planning)
- Show Type (Movie or Series)

A show can only be tracked once unlike games.

### **Describe the feature deliverables**

***Core logic***
- [x] Show tracking
  - [x] Add show to be tracked by its unique id with tracked information
  - [x] Delete show tracking
  - [x] Modify show tracking's information
  - [x] View all show trackings by user
    - [x] Paging support
    - [x] Filters and sorting support
  - [x] View show trackings made for a show by a user

***Tests***
- [x] Show tracking
  - [x] Add show to be tracked by its unique id with tracked information
  - [x] Delete show tracking
  - [x] Modify show tracking's information
  - [x] View all show trackings by user
  - [x] View show trackings made for a show by a user
