### ISSUE TITLE
[FEATURE] Game tracking

### ISSUE THREAD

**Issue by shazxrin** [very-indecisive-studios/tracktgt-server#8]
### **Feature description**

This feature allows users to track games. Games to be tracked will have the following tracked information:

- Hours played
- Format Owned (i.e Digital, Physical)
- Status (i.e Currently Playing, Playing, Paused, Planning)
- Game Ownership (i.e Owned, Loaned, Subscription (e.g Xbox Game Pass), Wishlist)

Games can be tracked multiple times of different platforms (e.g PS4, PC, Switch).

### **Describe the feature deliverables**

***Core logic***
- [x] Game tracking
  - [x] Add game to be tracked by its unique id and platform with tracked information
  - [x] Delete game tracking
  - [x] Modify game tracking's information
  - [x] View all game trackings by user
    - [x] Paging support
    - [x] Filters and sorting support
  - [x] View game trackings made for a game by a user

***Tests***
- [x] Game tracking
  - [x] Add game to be tracked by its unique id and platform with tracked information
  - [x] Delete game tracking
  - [x] Modify game tracking's information
  - [x] View all game trackings by user
  - [x] View game trackings made for a game by a user
